branch-defaults:
  master:
    environment: one-tap-api
    group_suffix: null
global:
  application_name: production
  default_ec2_keyname: cig-otp-key
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
