branch-defaults:
  master:
    environment: onetapapi
    group_suffix: null
global:
  application_name: one-tap-api
  default_ec2_keyname: cig-otp-key
  default_platform: Ruby 2.5 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
