branch-defaults:
  ADD-AUTH:
    environment: production
    group_suffix: null
  master:
    environment: production
global:
  application_name: one-tap-api
  default_ec2_keyname: one-tap-ec2-key
  default_platform: Ruby 2.4 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
