default: &default
  adapter: mysql2
  database: one-tap-api
  username: admin
  password: Glenside6!
  host: one-tap-db.cx8ky9vxpg7r.us-east-1.rds.amazonaws.com
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
